//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArenaHero.Utils.TypedScenes.Loader.Generated
{
    using ArenaHero.Utils.StateMachine;
    
    
    public class W1_Level_1Loader : ITypedLoader
    {
        
        public static void Load<TState, T>(GameStateMachine machine, T argument = default)
            where TState : State<GameStateMachine>
        
        {
            W1_Level_1.Load<TState, T>(machine, argument);
        }
    }
}
